manager_task/urls.py
from django.urls import path
from manager_task.views import (
    get_my_profile,
    register,
    create_task_view,
    SearchMyTasksView,
    worker_create_view,
    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDetailView,
    PositionDeleteView,
    TaskDetailView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeDeleteView,
    TaskTypeUpdateView,
    get_latitude_longitude,
    update_location,
)

urlpatterns = [
    path("registration/", register, name="register"),
    path("my-profile/", get_my_profile, name="my-profile"),
    path("", SearchMyTasksView.as_view(), name="my-page"),
    path("create-task/", create_task_view, name="create-task"),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="tasks-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="tasks-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="tasks-delete"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="tasks-detail"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path("workers/", WorkerListView.as_view(), name="workers-list"),
    path("workers/create/", worker_create_view, name="worker-create"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="positions-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/detail/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "get-location/",
        get_latitude_longitude,
        name="get-location",
    ),
    path('api/update-location/', update_location, name='update_location'),

]

app_name = "manager_task"

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include("manager_task.urls")),
]

website/urls.py
from django.urls import path
from website.views import (
    get_my_profile,
    register,
    create_task_view,
    SearchMyTasksView,
    worker_create_view,
    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDetailView,
    PositionDeleteView,
    TaskDetailView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeDeleteView,
    TaskTypeUpdateView,
)

urlpatterns = [
    path("registration/", register, name="register"),
    path("my-profile/", get_my_profile, name="my-profile"),
    path("", SearchMyTasksView.as_view(), name="my-page"),
    path("create-task/", create_task_view, name="create-task"),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="tasks-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="tasks-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="tasks-delete"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="tasks-detail"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path("workers/", WorkerListView.as_view(), name="workers-list"),
    path("workers/create/", worker_create_view, name="worker-create"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="positions-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/detail/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
]

app_name = "website"

mysite/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from website_it_manager_task.settings import AUTH_USER_MODEL


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        "Position",
        on_delete=models.CASCADE,
        related_name="workers",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name_plural = "workers"
        ordering = ["id"]

    def __str__(self):
        return self.username


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("urgent", "Urgent"),
        ("high", "High"),
        ("low", "Low"),
    ]
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(
        "TaskType", on_delete=models.CASCADE, related_name="tasks"
    )
    assignees = models.ManyToManyField(AUTH_USER_MODEL, related_name="tasks_assigned")

website/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from website import forms
from website.forms import (
    WorkerSearchForm,
    TaskForm,
    TaskSearchForm,
    CreateMyTaskForm,
    WorkerForm,
    RegistrationForm,
)
from website.models import Worker, Position, Task, TaskType


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    context_object_name = "task_detail"
    template_name = "website/index.html"
    success_url = reverse_lazy("website:tasks-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "website/task_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["total_tasks_count"] = Task.objects.all().count()
        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = (
            Task.objects.all().prefetch_related("assignees").select_related("task_type")
        )
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("website:tasks-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("website:tasks-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("website:tasks-list")
    template_name = "website/task_list_delete_confirm.html"


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "website/workers_list.html"
    paginate_by = 6
    context_object_name = "worker_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(initial={"username": username})
        context["total_workers_count"] = self.get_queryset().count()
        return context

    def get_queryset(self):
        queryset = Worker.objects.select_related("position").all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    context_object_name = "worker_detail"
    template_name = "website/worker_detail.html"


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    template_name = "website/worker_form.html"
    form_class = forms.WorkerForm

    def get_success_url(self):
        return reverse_lazy("website:worker-detail", kwargs={"pk": self.object.pk})


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    template_name = "website/worker_delete_confirm.html"
    success_url = reverse_lazy("website:workers-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    form_class = forms.PositionSearchForm
    context_object_name = "position_list"
    template_name = "website/positions_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["total_positions_count"] = self.get_queryset().count()
        context["search_form"] = forms.PositionSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = forms.PositionSearchForm(self.request.GET)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    success_url = reverse_lazy("website:positions-list")
    form_class = forms.PositionForm
    template_name = "website/positions_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = forms.PositionForm
    template_name = "website/positions_form.html"

    def get_success_url(self):
        return reverse_lazy("website:position-detail", kwargs={"pk": self.object.id})


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position
    form_class = forms.PositionForm
    template_name = "website/positions_detail.html"
    context_object_name = "position_detail"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("website:positions-list")
    template_name = "website/positions_delete_confirm.html"


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    form_class = forms.TaskTypeSearchForm
    context_object_name = "task_type_list"
    template_name = "website/task_type_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["all_task_types"] = TaskType.objects.all().count()
        context["search_form"] = forms.TaskTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = forms.TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    form_class = forms.TaskTypeForm
    success_url = reverse_lazy("website:task-type-list")
    template_name = "website/task_type_form.html"


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("website:task-type-list")
    template_name = "website/task_type_delete_confirm.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    form_class = forms.TaskTypeForm
    success_url = reverse_lazy("website:task-type-list")
    template_name = "website/task_type_form.html"


class SearchMyTasksView(LoginRequiredMixin, generic.ListView):
    model = Task
    form_class = forms.MyTaskSearchForm
    template_name = "website/index.html"
    context_object_name = "all_my_tasks"

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name", "")
        if name:
            queryset = queryset.filter(
                assignees=self.request.user, name__icontains=name
            )
        else:
            queryset = queryset.filter(assignees=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["total_my_tasks"] = Task.objects.filter(
            assignees=self.request.user
        ).count()
        context["search_form"] = forms.MyTaskSearchForm(initial={"name": name})
        return context


@login_required
def worker_create_view(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = WorkerForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Don't save to database yet
            password = form.cleaned_data["password"]  # Get password from form
            user.set_password(password)  # Hash the password
            user.save()  # Save user to database
            return redirect("website:workers-list")
    else:
        form = WorkerForm()
    return render(request, "website/worker_form.html", {"form": form})


def get_my_profile(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        return render(request, "website/my_profile.html")


@login_required
def create_task_view(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CreateMyTaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.save()
            task.assignees.add(
                request.user
            )  # Add the current user to the assignees ManyToManyField
            form.save_m2m()  # Save the ManyToManyField data
            return redirect("website:my-page")
    else:
        form = CreateMyTaskForm(initial={"assignees": [request.user.id]})
    return render(request, "website/create_my_task.html", context={"form": form})


def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("login")
    else:
        form = RegistrationForm()
    return render(request, "registration/registration.html", {"form": form})

templates/website/create_my_task.html
{% extends "website/base.html" %}
{% include 'includes/sidebar.html' %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Create task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/website/index.html
{% extends "website/base.html" %}
{% load crispy_forms_filters %}
{% include 'includes/sidebar.html' %}
{% block style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/task_list.css' %}">
{% endblock %}
{% block content %}
  <div class="container">
    <h1>All my tasks: {{ total_my_tasks }} <a href="{% url 'manager_task:create-task' %}">+</a></h1>
    <br>
    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-primary ml-3">
    </form>
    <br>
    {% if all_my_tasks %}
      <div class="row">
        <div class="col">
          <ul class="list-group">
            {% for task in all_my_tasks %}
              <li class="list-group-item custom-card">
                <div class="row">
                  <div class="col-md-8">
                    <h5>{{ task.name }}</h5>
                    <p class="mb-1">{{ task.description }}</p>
                    <p class="text-muted mb-1"><strong>Deadline:</strong> {{ task.deadline }}</p>
                    <p class="text-muted mb-1"><strong>Priority:</strong> {{ task.priority }}</p>
                    <p class="text-muted mb-1"><strong>Task Type:</strong> {{ task.task_type }}</p>
                  </div>
                  <div class="col-md-4">
                    <div class="d-flex justify-content-end">
                      <a href="{% url 'manager_task:tasks-update' pk=task.id %}" class="btn btn-outline-primary mr-2">Update</a>
                      <a href="{% url 'manager_task:tasks-delete' pk=task.id %}" class="btn btn-outline-danger">Delete</a>
                    </div>
                  </div>
                </div>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% else %}
      <br>
      <p>You don't have any task.</p>
    {% endif %}
  </div>
{% endblock %}

templates/website/my_profile.html
{% extends "website/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href="{% static "css/profile_page.css" %}">
{% endblock %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="profile-info mt-5">
          <div class="card border-0 rounded-20 shadow-lg">
            <div class="card-body text-center">
              <div class="profile-picture mb-4">
                <img src="https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/3da39-no-user-image-icon-27.png?fit=500%2C500&ssl=1" width="150" height="150" class="rounded-circle shadow" alt="Profile Picture">
              </div>
              <h2 class="profile-name mb-3">{{ user.username }}</h2>
              <p class="profile-email mb-2"><strong>Email:</strong> {{ user.email }}</p>
              <p class="profile-first-name mb-2"><strong>First Name:</strong> {{ user.first_name }}</p>
              <p class="profile-last-name mb-2"><strong>Last Name:</strong> {{ user.last_name }}</p>
              <div class="profile-action mt-4">
                <a href="{% url 'manager_task:worker-update' pk=user.id %}" class="btn btn-primary">Edit Profile</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/website/positions_delete_confirm.html
{% extends "website/base.html" %}
{% include "includes/sidebar.html" %}
{% block content %}
  <h1>Are you sure that you want to delete this position?</h1>
  <br>
  <br>
  <form action="{% url "manager_task:position-delete" pk=position.id %}" method="post">
    {% csrf_token %}
    <input type="submit" name="Yes, I'm sure" class="btn btn-danger">
  </form>

{% endblock %}

templates/website/positions_list.html
{% extends "website/base.html" %}
{% load crispy_forms_filters %}
{% include 'includes/sidebar.html' %}
{% block style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/positions_list.css' %}">
{% endblock %}
{% block content %}
  <div class="container">
    <h1>All Positions: {{ total_positions_count }} <a href="{% url 'manager_task:position-create' %}">+</a></h1>
    <br>
    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-primary ml-3">
    </form>
    <br>
    {% if position_list %}
      <div class="row">
        <div class="col">
          <ul class="list-group">
            {% for position in position_list %}
              <li class="list-group-item custom-card d-flex justify-content-between align-items-center">
                <h5>{{ position.name }}</h5>
                <p>
                  <a href="{% url 'manager_task:position-detail' pk=position.id %}" class="btn btn-outline-secondary mr-2">assignees</a>
                  <a href="{% url 'manager_task:position-update' pk=position.id %}" class="btn btn-outline-primary mr-2">update</a>
                  <a href="{% url 'manager_task:position-delete' pk=position.id %}" class="btn btn-outline-danger mr-2">delete</a>
                </p>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% else %}
      <p>No positions found</p>
    {% endif %}
  </div>
{% endblock %}

templates/website/task_list.html
{% extends "website/base.html" %}
{% load crispy_forms_filters %}
{% include 'includes/sidebar.html' %}
{% block style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/task_list.css' %}">
{% endblock %}
{% block content %}
  <div class="container">
    <h1>Total tasks in the team: {{ total_tasks_count }} <a
        href="{% url "manager_task:tasks-create" %}"><strong>+</strong></a></h1>
    <br>
    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-primary ml-3">
    </form>
    {% if task_list %}
      {% for task in task_list %}
        <div class="row">
          <div class="col-xl-12">
            <div class="card mb-3 card-body custom-card">
              <div class="row align-items-center">
                <div class="col-auto">
                  <a href="{% url 'manager_task:tasks-detail' pk=task.id %}">
                    <img src="https://www.bootdey.com/image/280x280/FF00FF/000000" class="width-90 rounded-3" alt="">
                  </a>
                </div>
                <div class="col">
                  <div class="overflow-hidden flex-nowrap">
                    <h6 class="mb-1">
                      {{ task.name }}
                    </h6>
                    <span class="text-muted d-block mb-2 small">
                      Deadline: {{ task.deadline }} <strong>(Importance level: {{ task.priority }})</strong>
                    </span>
                    <span class="text-muted d-block mb-2 small">
                      Task type: <strong>{{ task.task_type }}</strong>
                    </span>
                    <h6>
                      Description: {{ task.description }}
                    </h6>
                    <span class="test-muted d-block mb-2 small">
                      <i>
                        Assigned by:
                      </i>
                      {% for assignee in task.assignees.all %}
                        <a href="{% url 'manager_task:worker-detail' pk=assignee.id %}">
                          {{ assignee.username }}
                          {% if not forloop.last %}, {% endif %}
                        </a>
                      {% endfor %}
                    </span>
                    <div class="row align-items-center">
                      <div class="col-12">
                        <div class="row align-items-center g-0">
                          <div class="col">
                            <!-- Progress bar -->
                          </div>
                          <div class="col-auto">
                            <div class="btn-group" role="group" aria-label="Task actions">
                              <p>
                                <a href="{% url 'manager_task:tasks-update' pk=task.id %}" class="btn btn-outline-primary mr-2">Update</a>
                                <a href="{% url 'manager_task:tasks-delete' pk=task.id %}" class="btn btn-outline-danger">Delete</a>
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <br>
      <p>No tasks found</p>
    {% endif %}
  </div>
{% endblock %}

templates/website/task_type_list.html
{% extends "website/base.html" %}
{% load crispy_forms_filters %}
{% include 'includes/sidebar.html' %}
{% block style %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/task_type_list.css' %}">
{% endblock %}
{% block content %}
  <div class="container">
    <h1>All task types: {{ all_task_types }} <a href="{% url 'manager_task:task-type-create' %}">+</a></h1>
    <br>
    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-primary ml-3">
    </form>
    <br>
    {% if task_type_list %}
      <div class="row">
        <div class="col">
          <ul class="list-group">
            {% for task_type in task_type_list %}
              <li class="list-group-item custom-card d-flex justify-content-between align-items-center">
                <h5>{{ task_type.name }}</h5>
                <p>
                  <a href="{% url 'manager_task:task-type-update' pk=task_type.id %}" class="btn btn-outline-primary radius-15 mr-2">update</a>
                  <a href="{% url 'manager_task:task-type-delete' pk=task_type.id %}" class="btn btn-outline-danger radius-15 mr-2">delete</a>
                </p>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% else %}
      <br>
      <p>No task types found</p>
    {% endif %}
  </div>
{% endblock %}

templates/website/worker_delete_confirm.html
{% extends "website/base.html" %}
{% include "includes/sidebar.html" %}
{% block content %}
  <h1>Are you sure that you want to delete this user?</h1>
  <br>
  <br>
  <form action="{% url "manager_task:worker-delete" pk=worker.id %}" method="post">
    {% csrf_token %}
    <input type="submit" name="Yes, I'm sure" class="btn btn-danger">
  </form>

{% endblock %}

templates/website/workers_list.html
{% extends "website/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% include 'includes/sidebar.html' %}
{% block style %}
  <link rel="stylesheet" href="{% static 'css/workers_list.css' %}">
{% endblock %}
{% block content %}
  <div class="container">
    <h1>All workers: {{ total_workers_count }} <a href="{% url 'manager_task:worker-create' %}"><strong>+</strong></a></h1>
    <br>
    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-primary ml-3">
    </form>
    <br>
    {% if worker_list %}
      <div class="row">
        {% for worker in worker_list %}
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-body">
                <img src="https://i0.wp.com/digitalhealthskills.com/wp-content/uploads/2022/11/3da39-no-user-image-icon-27.png?fit=500%2C500&ssl=1" class="rounded-circle shadow" alt="" width="100" height="100">
                {% if worker.id == user.id %}
                  <h5 class="mt-3"><i>"Me"</i></h5>
                {% else %}
                  <h5 class="mt-3">{{ worker.first_name }} {{ worker.last_name }}</h5>
                {% endif %}
                <p>{{ worker.username }}</p>
                <p><strong>Position:</strong> {{ worker.position }}</p>
                <p><strong>Email:</strong> {{ worker.email }}</p>
                {% if worker.id == user.id %}
                  <a href="{% url 'manager_task:my-profile' %}" class="btn btn-outline-primary">Details</a>
                {% else %}
                  <a href="{% url 'manager_task:worker-detail' pk=worker.id %}" class="btn btn-outline-primary">Details</a>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <div class="alert alert-warning" role="alert">
        No workers found!
      </div>
    {% endif %}
  </div>
{% endblock %}