manager_task/urls.py
from django.urls import path
from manager_task.views import (
    get_my_profile,
    register,
    create_task_view,
    SearchMyTasksView,
    worker_create_view,
    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDetailView,
    PositionDeleteView,
    TaskDetailView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeDeleteView,
    TaskTypeUpdateView,
    get_latitude_longitude,
    update_location,
)

urlpatterns = [
    path("registration/", register, name="register"),
    path("my-profile/", get_my_profile, name="my-profile"),
    path("", SearchMyTasksView.as_view(), name="my-page"),
    path("create-task/", create_task_view, name="create-task"),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="tasks-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="tasks-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="tasks-delete"),
    path("tasks/<int:pk>", TaskDetailView.as_view(), name="tasks-detail"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path("workers/", WorkerListView.as_view(), name="workers-list"),
    path("workers/create/", worker_create_view, name="worker-create"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="positions-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/detail/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "get-location/",
        get_latitude_longitude,
        name="get-location",
    ),
    path('api/update-location/', update_location, name='update_location'),

]

app_name = "manager_task"

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include("manager_task.urls")),
]

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="pagination-container">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">Prev</a></li>
      {% endif %}
      <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">Next</a></li>
      {% endif %}
    </ul>
  </div>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li class="list-group-item user-info">
      <a href="{% url 'manager_task:my-profile' %}" class="nav-link">
        <strong>User: {{ user.username }}</strong>
      </a>
    </li>
    <li class="list-group-item">
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-block">Logout</button>
      </form>
    </li>
  {% else %}
    <li class="list-group-item">
      <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-block">Login</button>
      </form>
    </li>
  {% endif %}
  <br>

  <!-- Common menu items -->
  {% if user.id %}
    <li class="list-group-item">
      <a href="{% url "manager_task:my-page" %}" class="nav-link">My tasks</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}" class="nav-link">Login</a>
    </li>
  {% endif %}
  <li class="list-group-item">
    <a href="{% url 'manager_task:workers-list' %}" class="nav-link">All workers</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'manager_task:positions-list' %}" class="nav-link">All positions</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'manager_task:tasks-list' %}" class="nav-link">All Team's tasks</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'manager_task:task-type-list' %}" class="nav-link">All task's types</a>
  </li>
</ul>